name: Parse log file
description: Parse log file

outputs:
  content:
    description: "Log file content"
    value: ${{ steps.get-log-file.outputs.content }}

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: log-file
        path: resources
    - name: Get log file content
      shell: bash
      id: get-log-file
      run: |
        cd resources
        OUTPUT_STRING=$(cat log.txt)
        echo $OUTPUT_STRING
        echo "::set-output name=content::$OUTPUT_STRING"
