name: Assemble bff
description: Assemble bff

runs:
  using: 'composite'
  steps:
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Assemble bff
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble
    - name: Download web-static artifact
      uses: actions/download-artifact@v3
      id: download-artifact
      with:
        name: web-content
        path: ghactions-bff/src/main/resources
    - name: Unzip web-static artifact
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq ghactions-bff/src/main/resources/zip-web-content.zip -d ghactions-bff/src/main/resources

