name: Assemble bff
description: Assemble bff

runs:
  using: 'composite'
  steps:
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Assemble bff
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble
    - name: Download web-static artifact
      uses: actions/download-artifact@v3
      with:
        name: bff-resources-content
        path: web-static.zip
    - name: Unzip web-static artifact
      shell: bash
      run: unzip ./web-static.zip ghactions-bff/src/main/resources/

