name: Resolve frontend dependencies
description: Resolve frontend dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: package-lock.json
    - name: Resolve frontend dependencies
      shell: bash
      run: |
        cd ghactions-web && npm ci

