name: Create log file
description: Create log file


runs:
  using: composite
  steps:
  - name: Install Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'  
  - name: Run main
    run: python src/main.py
    shell: bash
  - name: List all directories
    run: ls
    shell: bash
