name: Frontend build
description: Frontend build

runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: package-lock.json
    - name: Build frontend dependencies
      shell: bash
      run: |
        cd ghactions-web
        npm ci
    - name: Copy frontend build to bff
      shell: bash
      run: |
        cd ghactions-web
        npm run build
        npm run copy-web-dist
    - name: Zip bff frontend build
      shell: bash
      run: zip web-static.zip ghactions-bff/src/main/resources/* -r
    - name: Upload web-static artifact
      uses: actions/upload-artifact@v3
      with:
        name: bff-resources-content
        path: web-static.zip
