name: Print log content
description: Print log content

inputs:
  log_data:
    description: "log content"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Print log data
      shell: bash
      run: echo ${{ toJSON(inputs) }}
