name: Run app
description: Run app

runs:
  using: 'composite'
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      id: download-artifact
      with:
        name: app-build
        path: ghactions-bff/build/libs
    - name: Log info
      shell: bash
      run: |
        cd ghactions-bff/build/libs
        ls
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Boot run
      shell: bash
      working-directory: ghactions-bff/build/libs
      run: java -jar ghactions-bff-0.0.1-SNAPSHOT.jar


