name: Run app
description: Run app

runs:
  using: 'composite'
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      id: download-artifact
      with:
        name: app-build
        path: ghactions-bff/build/libs
    - name: Log info
      shell: bash
      run: |
        cd ghactions-bff/build/libs
        ls

