name: Create hot patch branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Provide image tag
        default: main
        required: true

jobs:
  validate_hotpatch_branch:
    name: Validate hotpatch branch
    runs-on: ubuntu-latest
    steps:
      - name: Validate user input
        shell: bash
        run: |
          input="${{ github.event.inputs.branch}}"
          if [[ ! $input =~ ^hotpatch-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error ::Invalid branch. Only the 'hotpatch' branch is allowed for deployment."
            exit 1
          fi
  create_branch:
    name: Create hot path branch
    runs-on: ubuntu-latest
    steps:
      - name: Validate user input
        shell: bash
        run: |
          input="${{ github.event.inputs.branch}}"
          if [[ ! $input =~ ^[0-9]+[.][0-9]+[.]0$ ]]; then
            echo "::error ::Invalid tag format. Make sure that tag is specified as <<number>>.<<number>>.0 Patch version should be 0"
            exit 1
          fi
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - name: Create hotpatch branch 
        shell: bash
        run: |
            branch_name=hotpatch-${{ github.event.inputs.branch }}
            git config user.name "GithubActions"
            git config user.email "dsi@technipfmc.com"
            echo "Creating hotpatch branch"
            git checkout -b $branch_name
            git push --set-upstream origin $branch_name
