name: Create hot patch branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Select tag
        default: main
        required: true

jobs:
  create_branch:
    name: Create hot path branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - name: Create hotpatch branch 
        shell: bash
        run: |
          if [[ ! $input =~ ^[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Make sure that tag is specified as $number.$number. Patch versions are not allowed."
            exit 1
          else
            branch_name=hot_patch-${{ github.event.inputs.branch }}
            git config user.name "GithubActions"
            git config user.email "dsi@technipfmc.com"
            echo "Creating hotpatch branch"
            git checkout -b $branch_name
            git push --set-upstream origin $branch_name
          fi
