name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Select branch
        default: main
        required: true

jobs:
  say_hello:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        shell: bash
        run: echo "Hello"
  create_log_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: ./.github/actions/create-log-file
  parse_log_file:
    runs-on: ubuntu-latest
    needs: create_log_file
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - id: parse-log-data
        uses: ./.github/actions/parse-log-file
      - name: Log data
        shell: bash
        run: echo ${{ steps.parse-log-data.outputs.content }}
      - uses: ./.github/actions/print-log-content
        with:
          log-data: ${{ steps.parse-log-data.outputs.content }}
    outputs:
      log-output: ${{ steps.parse-log-data.outputs.content }}
  log_data_from_job:
    runs-on: ubuntu-latest
    needs: parse_log_file
    steps:
      - name: Log data from job
        shell: bash
        run: echo "This is log from job >>>> ${{ needs.parse_log_file.outputs.log-output }}"
