name: On push to master

on:
  push:
    branches:
      - master

jobs:
  resolve-backend-dependencies:
    name: Resolve backend dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at ${{ github.ref }}"
        uses: actions/checkout@v3
      - name: Resolve backend dependencies
        uses: ./.github/actions/resolve-backend-dependencies
  resolve-frontend-dependencies:
    name: Resolve frontend dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at ${{ github.ref }}"
        uses: actions/checkout@v3
      - name: Resolve frontend dependencies
        uses: ./.github/actions/resolve-frontend-dependencies
