name: On push to master

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  resolve-backend-dependencies:
    name: Resolve backend dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at ${{ github.ref }}"
        uses: actions/checkout@v3
      - name: Resolve backend dependencies
        uses: ./.github/actions/resolve-backend-dependencies
  resolve-frontend-dependencies:
    name: Resolve frontend dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at ${{ github.ref }}"
        uses: actions/checkout@v3
      - name: Resolve frontend dependencies
        uses: ./.github/actions/resolve-frontend-dependencies
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    needs: resolve-frontend-dependencies
    steps:
      - name: Checkout code at ${{ github.ref }}"
        uses: actions/checkout@v3
      - name: Build frontend
        uses: ./.github/actions/frontend-build
      - name: Log bff static files
        shell: bash
        run: |
          cd ghactions-bff/src/main/resources/static
          ls
  assemble-bff:
    name: Assemble bff
    runs-on: ubuntu-latest
    needs:
    - resolve-backend-dependencies
    - build-frontend
    steps:
      - name: Checkout code at ${{ github.ref }}"
        uses: actions/checkout@v3
      - name: Assemble backend
        uses: ./.github/actions/assemble-bff
      - name: Log bff static files
        shell: bash
        run: |
          echo "resources folder content"
          cd ghactions-bff/src/main/resources
          ls
          cd static
          echo "static folder content"
          ls
