name: on-merge-to-master

on:
  push:
    branches: [master]

jobs:
  say_hello:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        shell: bash
        run: echo "Hello"
  create_log_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/create-log-file
  parse_log_file:
    runs-on: ubuntu-latest
    needs: create_log_file
    steps:
      - uses: actions/checkout@v3
      - id: logData
        uses: ./.github/actions/parse-log-file
      - name: Log data
        shell: bash
        run: echo "This is your log file"
