name: Reuse job workflow
on:
  workflow_dispatch:


jobs:
  my_workflow:
    uses: ./.github/workflows/reusable-workflow.yml
  another_step:
    name: Another log
    runs-on: ubuntu-latest
    needs: my_workflow
    steps:
      - name: Log from another job
        shell: bash
        run: echo "Hello from another job"
      - uses: actions/download-artifact@v3
        with:
          name: log-file
          path: resources
      - name: Referencing to artifact
        shell: bash
        run: |
          cd resources
          echo "Here is a content of the log file >>> ${log.txt}"


