name: Publish stuff
run-name: "Name of the run"
on:
  workflow_dispatch:
    inputs:
      option_name:
        description: 'Name of the component to publish'
        required: true
        default: 'AudioStreamer'
        type: choice
        options:
          - 'OptionOne'
          - 'OptionTwo'
          - 'OptionThree'
  push:
    branches:
      - main

jobs:
  map-working-directory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: map
        run: | 
          ls -la
          chmod +x ./.github/workflows/path-mapper.sh
          ./.github/workflows/path-mapper.sh ${{ github.event.inputs.option_name }}
    outputs:
      working-directory: ${{ steps.map.outputs.working-directory }}

  build:
    name: Read variables
    runs-on: ubuntu-latest
    needs: map-working-directory
    steps:

      - name: Log variables
        run: |
          echo "Working directory: ${{ needs.map-working-directory.outputs.working-directory  }}"